# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ecflow_collector_pb2 as ecflow__collector__pb2


class EcflowCollectorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CollectStatus = channel.unary_unary(
        '/ecflow_collector.EcflowCollector/CollectStatus',
        request_serializer=ecflow__collector__pb2.StatusRequest.SerializeToString,
        response_deserializer=ecflow__collector__pb2.Response.FromString,
        )


class EcflowCollectorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CollectStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_EcflowCollectorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CollectStatus': grpc.unary_unary_rpc_method_handler(
          servicer.CollectStatus,
          request_deserializer=ecflow__collector__pb2.StatusRequest.FromString,
          response_serializer=ecflow__collector__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ecflow_collector.EcflowCollector', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
