# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ecflow_collector.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ecflow_collector.proto',
  package='ecflow_collector',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16\x65\x63\x66low_collector.proto\x12\x10\x65\x63\x66low_collector\"\xab\x01\n\rStatusRequest\x12\r\n\x05owner\x18\x01 \x01(\t\x12\x0c\n\x04repo\x18\x02 \x01(\t\x12\x0c\n\x04host\x18\x03 \x01(\t\x12\x0c\n\x04port\x18\x04 \x01(\t\x12\x0e\n\x06\x63onfig\x18\x05 \x01(\t\x12\x10\n\x08post_url\x18\x06 \x01(\t\x12\x18\n\x10\x63ontent_encoding\x18\x07 \x01(\t\x12\x14\n\x0c\x64isable_post\x18\x08 \x01(\x08\x12\x0f\n\x07verbose\x18\t \x01(\x08\"\x1a\n\x08Response\x12\x0e\n\x06status\x18\x01 \x01(\t2a\n\x0f\x45\x63\x66lowCollector\x12N\n\rCollectStatus\x12\x1f.ecflow_collector.StatusRequest\x1a\x1a.ecflow_collector.Response\"\x00\x62\x06proto3')
)




_STATUSREQUEST = _descriptor.Descriptor(
  name='StatusRequest',
  full_name='ecflow_collector.StatusRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='owner', full_name='ecflow_collector.StatusRequest.owner', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='repo', full_name='ecflow_collector.StatusRequest.repo', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='host', full_name='ecflow_collector.StatusRequest.host', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='ecflow_collector.StatusRequest.port', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='config', full_name='ecflow_collector.StatusRequest.config', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='post_url', full_name='ecflow_collector.StatusRequest.post_url', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content_encoding', full_name='ecflow_collector.StatusRequest.content_encoding', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='disable_post', full_name='ecflow_collector.StatusRequest.disable_post', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='verbose', full_name='ecflow_collector.StatusRequest.verbose', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=216,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='ecflow_collector.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ecflow_collector.Response.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=218,
  serialized_end=244,
)

DESCRIPTOR.message_types_by_name['StatusRequest'] = _STATUSREQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StatusRequest = _reflection.GeneratedProtocolMessageType('StatusRequest', (_message.Message,), dict(
  DESCRIPTOR = _STATUSREQUEST,
  __module__ = 'ecflow_collector_pb2'
  # @@protoc_insertion_point(class_scope:ecflow_collector.StatusRequest)
  ))
_sym_db.RegisterMessage(StatusRequest)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'ecflow_collector_pb2'
  # @@protoc_insertion_point(class_scope:ecflow_collector.Response)
  ))
_sym_db.RegisterMessage(Response)



_ECFLOWCOLLECTOR = _descriptor.ServiceDescriptor(
  name='EcflowCollector',
  full_name='ecflow_collector.EcflowCollector',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=246,
  serialized_end=343,
  methods=[
  _descriptor.MethodDescriptor(
    name='CollectStatus',
    full_name='ecflow_collector.EcflowCollector.CollectStatus',
    index=0,
    containing_service=None,
    input_type=_STATUSREQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ECFLOWCOLLECTOR)

DESCRIPTOR.services_by_name['EcflowCollector'] = _ECFLOWCOLLECTOR

# @@protoc_insertion_point(module_scope)
